DELETE http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Aytac Kamaci",
    "number": "551-219-8005"
}