POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "Rest",
  "author": "Aytac",
  "url": "bmomba",
  "likes": 45
}

###
POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "Rest",
  "author": "Aytac",
  "url": "bmomba",
  "likes": 45
}


###
POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "Spring",
  "author": "Yaren",
  "url": "zurna",
  "likes": 35
}