POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "Rest",
  "author": "Aytac",
  "url": "bmomba",
  "likes": 45
}

###
POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "Rest",
  "author": "Aytac",
  "url": "bmomba",
  "likes": 45
}


###
POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "Spring",
  "author": "Yaren",
  "url": "zurna",
  "likes": 35
}

####
PUT http://localhost:3001/api/blogs/627d181cf22ee8bec9aefb67
content-type: application/json

{
  "title": "HTML is easy",
  "author": "Aytac Kamaci",
  "url": "aa.com.rr.ds",
  "likes": 45
}